stepInstallDependenciesStep: &stepInstallDependenciesStep
  step:
    image: python:3.6
    name: Test
    caches:
      - pip
    script:
      - pip install -r requirements.txt
      - pytest --cov=. --cov-report=xml ./
    artifacts:
      - pytest-report.xml
      - coverage.xml

stepRunSonarScanner: &stepRunSonarScanner
  step:
    image: sonarsource/sonar-scanner-cli:latest
    name: Sonarqube scan
    script:
      - sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY:$BITBUCKET_BRANCH -Dsonar.login=$SONARQUBE_TOKEN

pipelines:
  pull-requests:
    '{master,dev,qa,github,feature/*}':
      - <<: *stepInstallDependenciesStep
      - <<: *stepRunSonarScanner

  branches:
    master:
      - <<: *stepInstallDependenciesStep
      - <<: *stepRunSonarScanner
    dev:
      - <<: *stepInstallDependenciesStep
      - <<: *stepRunSonarScanner
    github:
      - <<: *stepInstallDependenciesStep
      - <<: *stepRunSonarScanner

      - step:
          script:
            - git remote set-url origin git@github.com:UN-ICC/icc-oidc-bridge.git
            - git push origin master
    
